### ISSUE TITLE
Cannot reinitialise DataTable.  To retrieve the DataTables object for this table, pass no arguments or see the docs for bRetrieve and bDestroy

### ISSUE THREAD

**Issue by odendahl** [simplethemes/skeleton_wp#77]
Hi,

the Skeleton theme is really excellent.
However, today I found a problem and I need help fixing it.

After installing tablepress plugin and creating tables I receive the following error when starting the page with a table:

"DataTables warning (table id = 'tablepress-3'): Cannot reinitialise DataTable.
To retrieve the DataTables object for this table, pass no arguments or see the docs for bRetrieve and bDestroy".

Wordpress and all plugins are updated.
From what I can see, the problem is in the theme. I tried again after switching to the WordPress default theme TwentyThirteen and the error did not pop up.

Thanks for your help in advance.

Kind regards

Christian

**Comment by guoke12345** [comment]
You can take a look at this link.  
  https://datatables.net/manual/tech-notes/3  
I think it will help you.
